name: Pipeline de Build com Template da Empresa

on:
  push:
    tags:
      - 'v*'

jobs:
  use-template:
    uses: Carlos-Egger/empresa-pipelines/.github/workflows/template-build.yml@main
    with:
      image-name: docker.io/carlosegger/cliente-1-app:latest
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
